Repository ContentSquare/cp-ansible, pull requests merged in 2021-08, with the labels that each got.

#38 fix: apt update after adding new repo
  tasks/common/Debian.yml
Labels: size/XS

#39 fix: missing sudo for apt update
  tasks/common/Debian.yml
Labels: size/XS

#40 chore: manage upgrade version kafka
  tasks/common/Debian.yml
  tasks/common/main.yml
  vars/Debian.yml
Labels: size/M

#41 fix: condition to roll installation package
  tasks/common/Debian.yml
  tasks/common/main.yml
Labels: size/S
